/**
 * POST /api/sumo-recap
 * Body: { basho: "202609", day: 7, facts: {...} }  — see sumo.html's computeYesterdayFacts()
 *
 * Writes a short "themes of the day" recap of yesterday's top-division sumo bouts. The model
 * is given ONLY pre-computed facts (bout results, kinboshi, upsets, yūshō-race context, perfect
 * records) — it is never asked to read raw win/loss records itself, so it can't misread a
 * record or invent a result; its one job is turning clean facts into readable prose.
 *
 * Requires:
 *   - Secret  MISTRAL_API_KEY   (wrangler pages secret put MISTRAL_API_KEY)
 *   - KV binding  SUMMARIES      (optional — caches each day's recap so a page reload doesn't
 *                                 re-spend; the client also caches in localStorage regardless)
 *
 * If the key is missing it returns {wired:false} so the client shows placeholder copy and a
 * "not configured" note instead of erroring — same convention as the dining app's Mistral calls.
 */

const MODEL = 'mistral-medium-latest';
const CACHE_TTL = 60 * 60 * 24 * 3; // 3 days — a finished day's facts never change, but keep it short in case a bad recap needs to be regenerated by editing the prompt and redeploying

export async function onRequestPost(context) {
  const { request, env } = context;

  let body;
  try { body = await request.json(); } catch { return json({ error: 'bad_json' }, 400); }
  const basho = String(body.basho || '');
  const day = Number(body.day || 0);
  const facts = body.facts;
  if (!basho || !day || !facts) return json({ error: 'missing basho/day/facts' }, 400);

  if (!env.MISTRAL_API_KEY) {
    return json({ wired: false, message: 'MISTRAL_API_KEY not set on this deployment.' });
  }

  const cacheKey = 'recap:' + basho + '-' + day;
  if (env.SUMMARIES) {
    const cached = await env.SUMMARIES.get(cacheKey);
    if (cached) return new Response(cached, { headers: cors({ 'content-type': 'application/json' }) });
  }

  const sys = `You are a sumo commentator writing a short "themes of the day" recap for
English-speaking fans following a tournament (basho) live. You are given ONLY pre-computed,
verified facts below as JSON — bout results, notable upsets, kinboshi (a rank-and-file wrestler
beating a Yokozuna), the yūshō (championship) race, and anyone still undefeated. These facts are
already correct and complete for the day; do not add, guess, or infer any bout result, record,
rank, or kimarite that isn't in the JSON. If a category (e.g. kinboshi) is empty, don't mention it
just to fill space — only write about what's actually notable.

Write 2-4 short paragraphs, or a tight bulleted list if that reads better, covering the real
storylines: standout upsets, kinboshi if any, how the yūshō race moved, and any perfect records.
Keep it vivid but grounded — no invented color commentary about a bout's atmosphere or crowd
reaction that isn't implied by the facts. Plain text or simple markdown, no code fences.`;

  const userMsg = `FACTS for Day ${day} of ${facts.bashoName || basho}:\n${JSON.stringify(facts)}\n\nWrite the recap now.`;

  let data;
  try {
    const r = await fetch('https://api.mistral.ai/v1/conversations', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'authorization': 'Bearer ' + env.MISTRAL_API_KEY },
      body: JSON.stringify({
        model: MODEL,
        inputs: [
          { role: 'system', content: sys },
          { role: 'user', content: userMsg }
        ],
        store: false,
        completion_args: { temperature: 0.4 }
      })
    });
    if (!r.ok) {
      if (r.status === 429) {
        const retryAfter = Math.max(45, parseInt(r.headers.get('Retry-After') || '45', 10));
        return json({ wired: true, error: 'rate_limited', retry_after: retryAfter }, 429);
      }
      return json({ wired: true, error: 'upstream', status: r.status, detail: (await r.text()).slice(0, 300) }, 502);
    }
    data = await r.json();
  } catch (e) {
    return json({ wired: true, error: 'network', detail: String(e) }, 502);
  }

  let text = '';
  for (const o of (data.outputs || data.messages || data.entries || [])) {
    const isMsg = o.type === 'message.output' || o.role === 'assistant';
    if (!isMsg || o.content == null) continue;
    if (typeof o.content === 'string') text += o.content;
    else if (Array.isArray(o.content)) for (const ch of o.content) if (ch && ch.type === 'text' && ch.text) text += ch.text;
  }
  if (!text.trim()) return json({ wired: true, error: 'empty' }, 502);

  const out = JSON.stringify({ wired: true, text: text.trim(), day, basho });
  if (env.SUMMARIES) await env.SUMMARIES.put(cacheKey, out, { expirationTtl: CACHE_TTL });
  return new Response(out, { headers: cors({ 'content-type': 'application/json' }) });
}

export async function onRequestOptions() {
  return new Response(null, { headers: cors() });
}

function cors(h = {}) { return { 'access-control-allow-origin': '*', 'access-control-allow-methods': 'POST,OPTIONS', ...h }; }
function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), { status, headers: cors({ 'content-type': 'application/json' }) });
}
